# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MDNS_NETWORK_SERVICE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  	pod 'Ciao', '~> 2.1.1'

  target 'MDNS_NETWORK_SERVICETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MDNS_NETWORK_SERVICEUITests' do
    # Pods for testing
  end

end
